{
    "name": "HMS Lite",
    "version": "15.0.1.0.0",
    "depends": [
        "base",
        "sale_stock",
        "account",
        "web_timeline",
        "web",
        "mail",
        "web_domain_field",
        "portal",
        "stock",
        "product",
        "report_xlsx"
    ],
    "website": "https://mitcloud.com",
    "author": "Thandar Aung, Myat Mon Cho, Khant Sithu Aung, Min Khant Kyaw",
    "category": "Hotelia",
    "description": """ Hotel Management Software Integration """,
    # data files always loaded at installation
    "data": [
        "views/rooms.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
    ],
    # data files containing optionally loaded demonstration data
    "demo": [
        # 'demo/demo_data.xml',
    ],
    "summary": "Hotel Management Software Integration",
    "application": True,
    "qweb": ["hotelia/static/src/xml/calendar_ui.xml"],
    "license": "AGPL-3",
    "images": ["static/description/logo.png"],
    "installable": True,
    "auto_install": False,
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        # 'wizard/reservation_import.xml',
        # 'wizard/reg_import.xml',
        "wizard/reservation_report.xml",
        "wizard/reg_report_wizard.xml",
        "wizard/warning_wizard.xml",
        "wizard/transaction_report.xml",
        "wizard/guest_in_house.xml",
        "wizard/sale_summary_report.xml",
        "wizard/manager_report.xml",
        "wizard/rate_variant_wizard.xml",
        "wizard/departure_list_wizard.xml",
        "wizard/expected_departure_list.xml",
        "wizard/payment_detail_wizard.xml",
        "wizard/night_audit_wizard.xml",
        "wizard/year_plan_wizard.xml",
        "wizard/cashier_summary_wizard.xml",
        "wizard/guest_ledger_wizard.xml",
        # 'wizard/guest_list_wizard.xml',
        "wizard/bill_transfer.xml",
        "report/report.xml",
        "report/reservation_report_template.xml",
        "report/rate_variant_report.xml",
        "report/reg_report_template.xml",
        "report/guest_in_house_report_template.xml",
        "report/transaction_report_template.xml",
        "report/sale_summary_report_template.xml",
        "report/manager_report_template.xml",
        "report/departure_list_report.xml",
        "report/expected_departure_list.xml",
        "report/payment_detail_report.xml",
        "report/night_audit_report.xml",
        "report/bill_info_report.xml",
        "report/bill_print.xml",
        "report/year_plan_report.xml",
        "report/cashier_summary_report.xml",
        "report/guest_ledger_report.xml",
        "views/button_access.xml",
        "views/rooms.xml",
        "views/house_status.xml",
        "views/national.xml",
        "views/country.xml",
        "views/hms_name.xml",
        "views/amenity.xml",
        "views/calendar_tag.xml",
        # 'views/reservation.xml',
        "views/reservation_form_new.xml",
        "views/room_rate.xml",
        "views/room_setup.xml",
        "views/guest.xml",
        "views/currency.xml",
        # 'views/booking_chart_config.xml',
        "views/message.xml",
        "views/package.xml",
        "views/color.xml",
        "views/bill.xml",
        "views/payment.xml",
        "views/payment_line.xml",
        "views/guestline.xml",
        "views/room_chart.xml",
        "views/booking_chart.xml",
        "views/reservation_booking_chart.xml",
        "views/transaction.xml",
        "views/calendar_views.xml",
        "views/roomreserv.xml",
        "views/room_status.xml",
        "views/agentsetup.xml",
        "views/companysetup.xml",
        "views/arrival.xml",
        "views/waitlist.xml",
        "views/group_summary_view.xml",
        "views/folio.xml",
        "views/group_reserve.xml",
        # 'views/reservation_status.xml',
        # 'views/registration.xml',
        "views/registration_form_new.xml",
        "views/trans_inherit.xml",
        "views/no_show_list.xml",
        "views/reservationPopup.xml",
        # 'views/registrationPopup.xml',
        "views/dashboard_tag.xml",
        "views/housekeeping.xml",
        "views/quick_clean.xml",
        # 'views/systemconfig.xml',
        "views/night_audit.xml",
        "views/checkoutlist.xml",
        "views/transferlist.xml",
        "views/customer_type.xml",
        "views/room_transfer.xml",
        "views/transaction_line.xml",
        "views/cancel_transaction.xml",
        # 'views/functional_room/functional_rooms_setup.xml',
        # 'views/functional_room/functional_room_type.xml',
        # 'views/functional_room/functional_room_rate.xml',
        "views/function_room.xml",
        # 'views/login_templates.xml',
        "views/minibar_transaction.xml",
        # 'views/setting.xml',
        # 'views/timeline/setting_config.xml',
        "views/timeline/new_setting.xml",
        #'views/qweb_list_view.xml',
        #'views/website_menu.xml',
        # "views/calendar_reservation.xml",
        "views/delivery_order.xml",
        "views/product_category.xml",
        # "views/rptest.xml",
        "views/menu_items.xml",
        "views/bill_history.xml",
        "data/seq_data.xml",
        "data/customer_type_data.xml",
        "data/transaction_data.xml",
        # "data/group_readonly_cron.xml",
        "data/cron_excel_download.xml",
        # 'data/cron_night_audit.xml',
        "portal/guest_in_house_portal_views.xml",
        "portal/hotelia_portal_views.xml",
        "portal/reservations_portal_views.xml",
        "portal/sale_summary_portal_views.xml",
        "portal/transactions_portal_views.xml",
        "portal/registration_portal_views.xml",
        "portal/rate_variant_portal_views.xml",
        "portal/departure_portal_views.xml",
        "portal/edeparture_portal_views.xml",
        "portal/payment_detail_portal.xml",
        "portal/cashier_summary_portal_views.xml",
        "portal/guest_ledger_portal_views.xml",
        "portal/manager_portal_views.xml",
        "portal/year_plan_portal_views.xml",
    ],
    "sequence": -100,
    "assets": {
        "hotelia.assets": [
            "hotelia/static/src/scss/hmslite.scss",
        ],
        "web.assets_backend": [
            "hotelia/static/src/js/button_no_save.js",
            "hotelia/static/src/js/group_summary.js",
            # 'hotelia/static/src/js/calendar_chart.js',
            "hotelia/static/src/js/hotel_room_summary.js",
            "hotelia/static/src/js/booking_chart.js",
            "hotelia/static/src/js/tree_view_button.js",
            "hotelia/static/src/js/widget_guest.js",
            "hotelia/static/src/js/widget_registration.js",
            "hotelia/static/src/js/room_pop_up_widget.js",
            "hotelia/static/src/js/message_reg_widget.js",
            "hotelia/static/src/js/functional_room_modal.js",
            "hotelia/static/src/css/style.css",
            "hotelia/static/src/js/group_popup_widget.js",
            "hotelia/static/src/js/package_popup_widget.js",
            "hotelia/static/src/js/confirm_alert.js",
            "hotelia/static/src/js/web_widget_timepicker.js",
            "hotelia/static/src/js/color.js",
            "hotelia/static/src/js/dashboard.js",
            "hotelia/static/src/scss/dashboard.scss",
            # "hotelia/static/src/js/chart.min.js",
            "hotelia/static/src/js/quick_clean.js",
            "hotelia/static/src/js/custom_tree.js",
            "hotelia/static/src/js/two_fields.js",
            "hotelia/static/src/js/truncated_html.js",
            "hotelia/static/src/js/inc_widget.js",
            "hotelia/static/src/js/room_transfer.js",
            "hotelia/static/src/js/my_widget.js",
            "hotelia/static/src/js/custom_modal.js",
            "hotelia/static/src/css/my_widget.css",
            # "hotelia/static/src/js/controlpanel.js",
            "hotelia/static/src/scss/inc_widget_style.scss",
            "hotelia/static/src/scss/custom_form.scss",
            "hotelia/static/src/js/custom_form.js",
            "hotelia/static/src/css/hotelia.css",
        ],
        "web.assets_qweb": [
            "hotelia/static/src/xml/dashboard_ui.xml",
            # 'hotelia/static/src/xml/calendar_ui.xml',
            "hotelia/static/src/xml/group_summary.xml",
            "hotelia/static/src/xml/hotel_room_summary.xml",
            "hotelia/static/src/xml/booking_chart.xml",
            "hotelia/static/src/xml/widget_search_template.xml",
            "hotelia/static/src/xml/reg_button_save.xml",
            "hotelia/static/src/xml/discard_cancle_button.xml",
            "hotelia/static/src/xml/group_popup_widget.xml",
            "hotelia/static/src/xml/package_popup_widget.xml",
            "hotelia/static/src/xml/quick_clean.xml",
            "hotelia/static/src/xml/list_view_without_cpanel.xml",
            "hotelia/static/src/xml/inc_widget_template.xml",
        ],
    },
    "license": "AGPL-3",
    "images": ["static/description/logo.png"],
    "installable": True,
    "auto_install": False,
}
